upstreams:
  - id: backend
    targets:
      - host: 127.0.0.1
        port: 3000
        weight: 1

servers:
  - id: main-server
    bind_address: 127.0.0.1
    port: 8080
    cache:
      max_size: 5
      default_ttl_seconds: 600
    routes:
      - domains: ["api.home.arpa"]
        paths: ["/api"]
        upstream: backend
